services:
  - type: web
    name: m4a-to-mp3-converter
    env: docker
    plan: free
    buildCommand: "./build.sh"
    startCommand: "java -jar target/m4a-to-mp3-converter-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: FFmpeg_Path
        value: "/usr/bin/ffmpeg"
